CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS drive_access (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  access_level VARCHAR(20) DEFAULT 'read',
  granted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
